/*
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

*/

//Soln using map TC O(N) SC O(1)
class Solution {
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> map = new HashMap();
        for (char c: s.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }
        for (char c: t.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0)-1);
            if (map.get(c) == -1) return c;
        }
        return '0';
    }
}

//Soln using bit manipulation TC O(N) SC O(1)
class Solution {
    public char findTheDifference(String s, String t) {
        char ch = 0;
        for (char c: s.toCharArray()) {
            ch ^= c;
        }
        for (char c: t.toCharArray()) {
            ch ^= c;
        }
        return ch;
    }
}
